version: "3"

services:
  homeport-api-php:
    build:
      context: .
      dockerfile: "php.Dockerfile"
      args:
        APP_VERSION: latest
    image: blendstudio.azurecr.io/homeport-api-php
    container_name: homeport-api-php
    env_file:
      - api-variables.env

  homeport-api-nginx:
    build:
      context: .
      dockerfile: "nginx.Dockerfile"
      args:
        APP_VERSION: latest
    image: blendstudio.azurecr.io/homeport-api-nginx
    container_name: homeport-api-nginx
    depends_on:
      - homeport-api-php
